### ISSUE TITLE
Sample not working in my application

### ISSUE THREAD

**Issue by elmor34** [ivanthecrazy/ion-place-autocomplete#3]
Your application works fine when run standalone even if I run it with Ionic 1.2.4.
But when I move same code to my application I get the following error.
So any idea?

>TypeError: Cannot read property 'length' of undefined
    at Object.<anonymous> (http://localhost:8100/lib/ion-place-autocomplete-master/ion-place-autocomplete.js:46:54)
    at Object.arguments.(anonymous function) [as fn] (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:1953:36)
    at Scope.$digest (http://localhost:8100/lib/ionic/js/ionic.bundle.js:28995:29)
    at Scope.scopePrototype.$digest (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:1972:23)
    at Scope.$apply (http://localhost:8100/lib/ionic/js/ionic.bundle.js:29263:24)
    at Scope.scopePrototype.$apply (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:2035:22)
    at done (http://localhost:8100/lib/ionic/js/ionic.bundle.js:23676:47)
    at completeRequest (http://localhost:8100/lib/ionic/js/ionic.bundle.js:23848:7)
    at XMLHttpRequest.requestLoaded

**Comment by ivanthecrazy** [comment]
@elmor34 
Can you please update to the latest version and try again? this should be fixed with latest commit.
